name: Deploy to AWS S3

on:
  push:
    branches: [ main ]
  # Removed pull_request trigger - typically you only deploy on main pushes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Hardcoded version, or use '18' if preferred
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to AWS S3
      run: |
        # Sync files with appropriate cache headers
        aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete \
          --cache-control "public,max-age=31536000,immutable" \
          --exclude "*.html" \
          --exclude "*.json"
        
        # Upload HTML files with no-cache to ensure updates are seen immediately
        aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} \
          --cache-control "public,max-age=0,must-revalidate" \
          --include "*.html" \
          --include "*.json"